# Generated by Django 4.1.7 on 2023-03-09 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0002_authors_date_of_birth_authors_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 19, 19, 49, 76339)),
        ),
        migrations.AlterField(
            model_name='authors',
            name='date_of_death',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 19, 19, 49, 76339)),
        ),
        migrations.AlterField(
            model_name='books',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 19, 19, 49, 77336)),
        ),
    ]
