# Generated by Django 4.1.7 on 2023-03-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0007_alter_authors_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country_name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
