# Generated by Django 4.1.7 on 2023-03-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0008_alter_countries_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='authors',
            old_name='author_surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='country_name',
            new_name='name',
        ),
    ]
