# Generated by Django 4.1.7 on 2023-03-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0009_rename_author_name_authors_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='webofbooks/static/bookcovers/default.jpg', upload_to='webofbooks/static/bookcovers'),
        ),
    ]
