# Generated by Django 4.1.7 on 2023-03-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0012_books_date_added_alter_authors_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='bookcovers/default.jpg', upload_to='bookcovers/'),
        ),
    ]
