# Generated by Django 4.1.7 on 2023-03-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0013_alter_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(default='bookweb/static/webofbooks/default.jpg', upload_to='bookweb/static/webofbooks/'),
        ),
    ]
