# Generated by Django 4.1.7 on 2023-03-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0017_alter_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
