# Generated by Django 4.1.7 on 2023-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0019_alter_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
