# Generated by Django 4.1.7 on 2023-03-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webofbooks', '0020_alter_authors_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksread',
            old_name='used_id',
            new_name='user_id',
        ),
    ]
